### ISSUE TITLE
Nextflow and TRUE/FALSE flags in R

### ISSUE THREAD

**Issue by cjfields** [HPCBio/16S-rDNA-dada2-pipeline#1] opened 2018-05-18 15:15 UTC
Boolean parameter flags for Groovy, such as `true` or `false`, are not being interpolated correctly within the Rscript section of processes (R expects upper-case boolean).  So particular parameters relying on this switch are broken, such as `trimOverhang` and `rmPhiX` and are currently hard-coded.  

```
> TRUE
[1] TRUE
> true
Error: object 'true' not found
> 
```

**Comment by cjfields** [comment] 2018-05-18 15:19
@grbot something to be aware of; I'm checking the Nextflow Google group on this one.

**Comment by kviljoen** [comment] 2018-10-17 11:57
Hi Chris,

Can you show me how you know this is broken, does the following code not take care of this issue?
    #Variable selection from CLI input flag --trimOverhang
    if("${params.trimOverhang}"=="F"){
      trimOverhang <- FALSE
    } else if("${params.trimOverhang}"=="T"){
      trimOverhang <- TRUE
    }  
    print(trimOverhang)

**Comment by kviljoen** [comment] 2018-10-17 13:42
Thanks Chris. Agreed, that is potentially confusing. Also, I see I did 'F' and T' for `--trimOverhang` but not for `rmPhiX` which I've now fixed in https://github.com/kviljoen/16S-rDNA-dada2-pipeline/blob/dev/main.nf so hopefully its working. The problem is that Nextflow automatically writes 'TRUE' or TRUE as true, which is then seen as a (non-exisiting) object by R. But yes, other than the current workaround not sure how to change this to something more user-friendly.

**Comment by cjfields** [comment] 2018-10-17 13:53
@kviljoen I think it would require a Groovy helper function to catch them early on (otherwise you'll end up writing those conditionals for each R script block.  Phil Ewels has written a few in some of the nf-core code to do rudimentary tasks, one of us could ask about this maybe via the nextflow gitter channel (he and Paolo tend to be there quite a bit).

**Comment by pditommaso** [comment] 2018-10-19 07:01
My advice for big chunks of foreign code is to managed as an external script and save the project `bin/` folder. It makes the code more readable and easier to test. The arguments can be then specified as command line option. Se an example [here](https://github.com/cbcrg/kallisto-nf/blob/master/kallisto.nf#L139) and [here](https://github.com/cbcrg/kallisto-nf/blob/master/bin/sleuth.R#L4).

**Comment by cjfields** [comment] 2018-10-19 21:50
Thx @pditommaso !

**Comment by cjfields** [comment] 2018-11-14 21:37
Short term fix is to use `as.logical()` from the input string:

```
> TRUE
[1] TRUE
> true
Error: object 'true' not found
> as.logical("true")
[1] TRUE
> as.logical("false")
[1] FALSE
> as.logical("T")
[1] TRUE
> as.logical("F")
[1] FALSE
```

I'm still oddly seeing issues with @kviljoen fix (it works for them), the following seems to work within the embedded R code:

```
rm.phix <- as.logical(${params.rmPhiX})
```

Long-term, we need to move to a script but I think we can make a separate issue for it.

**Closed** 2018-11-14 21:38 UTC
Labels: Low Priority, annoyance, bug
